language: python

python:
- 3.7

# checkout all of the history, not just last 50 commits
# needed to help us work out the correct docker tags for
# things that haven't changed in a long time
git:
  depth: false

services:
- docker

cache: pip

install:
- |
  # Stage 1: Install pytest + test dependencies
  # pip install -U pyyaml pytest requests sphinx sphinx-autobuild
  pip install -r dev-requirements.txt
script:
- |
  # Build staginghub image
  python ./deploy.py --no-setup --build staginghub
- |
  # Build documentation
  pushd docs && make html && popd

# We are using before_deploy instead of script or deploy
# since before_deploy gives us nice, folded log views,
# which neither script nor deploy seems to!
# Tasks here only run after merge
before_deploy:
- |
  # Stage 1: Install gcloud SDK
  curl -L https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-173.0.0-linux-x86_64.tar.gz | tar --directory ${HOME} --extract --gzip --file -
- |
  # Stage 1: Install Kubectl
  mkdir -p ${HOME}/bin
  curl -L https://storage.googleapis.com/kubernetes-release/release/v1.18.2/bin/linux/amd64/kubectl > ${HOME}/bin/kubectl
  chmod +x ${HOME}/bin/kubectl
- |
  # Stage 1: Install helm
  curl -L https://storage.googleapis.com/kubernetes-helm/helm-v2.16.7-linux-amd64.tar.gz | tar --directory ${HOME} --extract --gzip --file -
  mv ${HOME}/linux-amd64/helm ${HOME}/bin/helm
- |
  # Stage 1: Install git-crypt
  curl -L https://github.com/minrk/git-crypt-bin/releases/download/0.5.0/git-crypt > git-crypt
  echo "46c288cc849c23a28239de3386c6050e5c7d7acd50b1d0248d86e6efff09c61b  git-crypt" | shasum -a 256 -c -
  chmod +x git-crypt
  mv git-crypt ${HOME}/bin/git-crypt
- |
  # Stage 2, Step 1: Unlock our secret files!
  # Travis allows encrypting only one file per repo (boo) so we use it to
  # encrypt our git-crypt key
  cd ${TRAVIS_BUILD_DIR}
  openssl aes-256-cbc -K $encrypted_7893ea004563_key -iv $encrypted_7893ea004563_iv -in travis/crypt-key.enc -out travis/crypt-key -d
  git-crypt unlock travis/crypt-key
- |
  # Stage 2, Step 2: Set up helm!
  helm init --client-only
  helm repo add jupyterhub https://jupyterhub.github.io/helm-chart
  helm repo update
- |
  # Stage 3, Step 1: Build & push image, then deploy staginghub
  python ./deploy.py --build --push staginghub
  python ./deploy.py --deploy staginghub
# - |
#   # Stage 3, Step 2: Build & push image, then deploy earth-analytics-hub
#   python ./deploy.py --build --push ea-hub
#   python ./deploy.py --deploy ea-hub
# - |
#   # Stage 3, Step 4: Deploy monitoring of the hubs
#   python ./deploy.py --deploy monitoring


env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - PATH=${HOME}/google-cloud-sdk/bin:${HOME}/bin:${PATH}

deploy:
  provider: script
  script: /bin/true
  on:
    branch:
      - staging

branches:
  only:
    - staging
